#!/usr/bin/env bash
set -Eeuo pipefail

ENV_FILE=${MC_PANEL_ENV_FILE:-/etc/mc-panel/panel.env}
CURRENT=${MC_PANEL_CURRENT:-/opt/mc-panel/current}

if [[ ! -f $ENV_FILE || -L $ENV_FILE ]]; then
    echo "Panel environment file is missing or unsafe." >&2
    exit 1
fi
if [[ $(stat -c '%U:%G:%a' "$ENV_FILE") != root:mc-panel:640 ]]; then
    echo "Panel environment ownership or mode is unsafe." >&2
    exit 1
fi
if [[ ! -x $CURRENT/.venv/bin/mc-panel-admin ]]; then
    echo "Installed panel CLI is missing." >&2
    exit 1
fi

set -a
# The file is generated by mc-panel and is root-owned, non-writable by the service user.
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

exec "$CURRENT/.venv/bin/mc-panel-admin" fingerprint
