from __future__ import annotations

from typing import Any, Protocol


class AdapterOperationError(RuntimeError):
    def __init__(self, code: str, message: str, details: dict[str, Any] | None = None) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details or {}


class MinecraftAdapter(Protocol):
    def fingerprint(self) -> str: ...

    def get_status(self) -> dict[str, Any]: ...

    def get_metrics(self) -> dict[str, Any]: ...

    def list_players(self) -> dict[str, Any]: ...

    def get_player_activity(self, days: int = 7) -> dict[str, Any]: ...

    def scan_player_activity(self, days: int = 30) -> dict[str, Any]: ...

    def read_logs(
        self, source: str = "latest", lines: int = 200, severity: list[str] | None = None
    ) -> dict[str, Any]: ...

    def list_crash_reports(self) -> list[dict[str, Any]]: ...

    def read_crash_report(self, report_id: str) -> dict[str, Any]: ...

    def list_mods(self) -> list[dict[str, Any]]: ...

    def get_mod_upload(self, upload_id: str) -> dict[str, Any]: ...

    def get_properties(self) -> dict[str, Any]: ...

    def list_whitelist(self) -> list[str]: ...

    def list_operators(self) -> list[str]: ...

    def list_backups(self) -> list[dict[str, Any]]: ...

    def get_backup_schedule(self) -> dict[str, Any]: ...

    def get_backup_status(self) -> dict[str, Any]: ...

    def execute(self, action: str, params: dict[str, Any]) -> dict[str, Any]: ...
